`define instr_addr_misalign 'h0
`define instr_access_fault 'h1
`define illegal_instr 'h2
`define load_addr_misalign 'h4
`define load_access_fault 'h5
`define store_amo_addr_misalign 'h6
`define store_amo_access_fault 'h7
//`define breakpoint 3
//`define env_call_u_mode 8
//`define env_call_m_mode B
